site_name: Pattern Builder

pages:
- Home: index.md
- Pattern Kit: pattern_kit.md
- PHP Library: pattern_builder_library.md
- Drupal Module: pattern_builder_module.md
- Drupal Schema Importer: pattern_builder_importer.md
- Drupal Usage: using_pattern_builder.md

theme: readthedocs
